name: 'Feature'
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '*'
      - '!master'
      - '!v*.'
      - '!*.*.*'
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: setup node 14 environment
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install
        run: npm ci --ignore-scripts
      - name: start unit test
        run: npm run test:ci

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: setup node 14 environment
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install
        run: npm ci --ignore-scripts
      - name: build lib & app
        run: |
          npm run build:lib
          npm run build:app-prerender
      - name: start e2e test
        run: |
          docker run -p 127.0.0.1:80:80 -d $(docker build -q .)
          docker run -e BASE_RUL=http://127.0.0.1 \
                     -v ./e2e/reports:/opt/robotframework/reports:Z \
                     -v ./e2e/tests:/opt/robotframework/tests:Z ppodgorsek/robot-framework:3.8.0
