name: 'Feature'
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '*'
      - '!master'
      - '!v*.'
      - '!*.*.*'
jobs:
  build-fe:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install
        run: npm ci --ignore-scripts
      - name: unit test
        run: npm run test:ci
      - name: build lib & app
        run: |
          npm run build:lib
          npm run build:app-prerender
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  build-docker:
    needs:
      - build-fe
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ngrx-store-storagesync:latest

  e2e:
    needs:
     - build-docker
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: start frontend container
        uses: addnab/docker-run-action@v3
        with:
          image: ngrx-store-storagesync:latest
          options: -p 80:80
      - name: start e2e test container
        uses: addnab/docker-run-action@v3
        with:
          image: ppodgorsek/robot-framework:3.8.0
          options: -e BASE_RUL=http://127.0.0.1 -v ${{ github.workspace }}/e2e/tests:/opt/robotframework/tests:Z -v ${{ github.workspace }}/e2e/reports:/opt/robotframework/reports:Z
