name: Firebase Hosting
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci --ignore-scripts --legacy-peer-deps
          npm run test:ci
          npm run build
          $(npm bin)/codecov -f coverage/coverage-final.json
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NGRX_STORE_STORAGESYNC }}'
          channelId: live
          projectId: ngrx-store-storagesync
