name: npm-publish
'on':
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - run: npm ci --legacy-peer-deps --ignore-scripts
      - run: npm run test:ci
      - run: npm run build && npm run build:lib
      - run: |
           cd dist/ngrx-store-storagesync
           ls -ltra .
           npm publish
