name: '@larscom/ngrx-store-storagesync'

on:
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm run build:lib
      - run: npm run build:app-prerender
      - run: npm run test -- --code-coverage --watch=false
      - uses: ./.github/actions/create-image.yml
